version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "terrain-splitter"
resolve_s3 = true
s3_prefix = "terrain-splitter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\" AllowedOrigin=\"*\" RootParallelWorkers=\"12\" RootParallelGranularity=\"subtree\" RootParallelMaxInflight=\"16\" LambdaInvokeReadTimeoutSec=\"300\" NestedLambdaMinCells=\"64\" NestedLambdaMaxInflight=\"8\" ExactPostprocessTopK=\"8\" ExactCandidateMaxInflight=\"8\""
image_repositories = []

[staging.build.parameters]
cached = true
parallel = true

[staging.deploy.parameters]
stack_name = "terrain-splitter-staging"
resolve_s3 = true
s3_prefix = "terrain-splitter-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"staging\" AllowedOrigin=\"*\" RootParallelWorkers=\"12\" RootParallelGranularity=\"subtree\" RootParallelMaxInflight=\"16\" LambdaInvokeReadTimeoutSec=\"300\" NestedLambdaMinCells=\"64\" NestedLambdaMaxInflight=\"8\" ExactPostprocessTopK=\"8\" ExactCandidateMaxInflight=\"8\""
image_repositories = []
